### ISSUE TITLE
breaking change in 1.0.8 ?

### ISSUE THREAD

**Issue by disoul** [muaz-khan/getStats#19]
My application is crashed because i used `"getstate": "^1.0.6"` in my `package.json`.
I think `1.0.6` to `1.0.8` should just be a `PATCH` version in [Semantic Versioning](https://semver.org/). But it seems that its behavior has changed.

here is `1.0.6` [code](https://github.com/muaz-khan/getStats/blob/1.0.6/getStats.js#L122-L136)
```javascript
    if (arguments[0] instanceof RTCPeerConnection) {
        peer = arguments[0];

        if (!!navigator.mozGetUserMedia) {
            mediaStreamTrack = arguments[1];
            callback = arguments[2];
            interval = arguments[3];
        }

        if (!(mediaStreamTrack instanceof MediaStreamTrack) && !!navigator.mozGetUserMedia) {
            throw '2nd argument is not instance of MediaStreamTrack.';
        }
    } else if (!(mediaStreamTrack instanceof MediaStreamTrack) && !!navigator.mozGetUserMedia) {
        throw '1st argument is not instance of MediaStreamTrack.';
    }
```
this arguments type check support `getStats(RTCPeerConnection, MediaStreamTrack, ...)` **and** `getStats(MediaStreamTrack, ...)`
but in `1.0.8` [code](https://github.com/muaz-khan/getStats/blob/70dc05621e8a5b62e9c70703d9d78a97be9ea003/getStats.js#L132-L142)
```javascript
    if (!(arguments[0] instanceof RTCPeerConnection)) {
        throw '1st argument is not instance of RTCPeerConnection.';
    }

    peer = arguments[0];

    if (arguments[1] instanceof MediaStreamTrack) {
        mediaStreamTrack = arguments[1]; // redundant on non-safari
        callback = arguments[2];
        interval = arguments[3];
    }
```
this type check only support `getStats(RTCPeerConnection, MediaStreamTrack, ...)`
`getStats(MediaStreamTrack, ...)` will throw error `1st argument is not instance of RTCPeerConnection.`

**Comment by muaz-khan** [comment]
Are you using `peer.getStats`? AFAIK, first parameter must be RTCPeerConnection object if you're using `getStats` as a global function. E.g.

```javascript
getStasts(RTCPeerConnection, callback);
getStasts(RTCPeerConnection, MediaStreamTrack callback);
```
Only above two formats are supported.

If you're using `peer.getStats` then please replace it with global function. It may fix the issue.

**Comment by disoul** [comment]
Thanks, 
You are right, replacing it does solved my problem
But what I want to express is this change should be reflected in the version number.
In fact, the code in your README can't even run under `1.0.8`.
